"use client"
import { Roboto } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Bootstrapjs from '../../components/Bootstrapjs'

const roboto = Roboto({
  weight: ['100', '400', '500', '700', '900'],
  subsets: ['latin'],
  display:'swap'
})
// export const metadata = {
//   title: 'Country Detail App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Country Details App</title>
        <meta name='description' content='Description' />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,300&display=swap" rel="stylesheet"></link>
      </head>
      <Bootstrapjs />
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
